name: arm-none-ebi-gcc
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.6.1
        with:
          release: 'latest'
          path-env-var: ARM_NONE_EABI_GCC_PATH
      - run: arm-none-eabi-gcc --version
      - name: make compile 
        run: make DEBUG=1 -j2 all  GCC_PATH=$ARM_NONE_EABI_GCC_PATH