name: arm-none-ebi-gcc
run-name: compile project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.6.1
        with:
          release: 'latest'
      - run: arm-none-eabi-gcc --version